### ISSUE TITLE
What is the assignments ?

### ISSUE THREAD

**Issue by ShubhamShaswat** [Taiyo-ai/ts-mesh-pipeline#6]
Hey
I got this assignment with a google docs links attached to after applying for the Data Engineer role at the Internshala.I was looking at the docs mentioning the tasks.However, I am not sure about the specificity of my task. 
I am interested in the "3. Sample processing script executed on a small subset of the data set".After reading the Readme.MD and WIKI, I am still not sure about the next step.
So, can you tell me more about my task such as what kind of data we are dealing with here and what are the processing steps we are looking for ?
The reason I am asking this question here is because I haven't received any response form them on the website Internshala.

**Comment by KayvanShah1** [comment]
The third statement states that data processing scripts are meant to be tested on a small sample or subset of the available data that is to extract from the source of your choice. The type and nature of data you have to deal with solely depend upon your choice.

The section "Different Blocks of ETL pipeline" gives a detailed explanation about the different processing steps involved and which ones are to be implemented depending upon the data source which you chose.

**Comment by KayvanShah1** [comment]
I hope you have found the answer to your question. Closing the issue...
